### ISSUE TITLE
C 언어 커널 부팅 테스트 메세지 앞부분이 짤립니다.

### ISSUE THREAD

**Issue by EugeneChung** [kkamagui/mint64os#16]
![image](https://user-images.githubusercontent.com/3361146/145696456-d4525545-e53b-4279-9be1-81bc0c843ada.png)

1권 7장에서 C 언어 커널 띄우면서 video memory `0xb8000` 에 문자열을 찍을 때, 앞 글자 2개가 짤려서 찍힙니다.
그런데 어느 부분이 문제일지 전혀 예상이 안 되어 답답한 마음에 여기에 올려봅니다. ^^;;;

macOS Monterey, gcc 11.2.0, QEMU 6.1.0 등 최신 버전을 쓰고 있긴 하지만 boot loader나 entrypoint 쪽은 문제없이 프린팅이 되고 있어서 qemu 버전 차이는 아닐 거라고 예상하고 있습니다.
loader script를 gcc 11.2.0에 있는 걸 가져와서 책 참고하면서 고쳐서 썼는데 혹시 이 부분에서 차이가 있을까 해서  https://github.com/kkamagui/mint64os/blob/master/01.Kernel32/elf_i386.x 을 써도 결과는 똑같았습니다.

- types.h
```c
#ifndef MINTOS64_TYPES_H
#define MINTOS64_TYPES_H

#define BYTE unsigned char
#define WORD unsigned short
#define DWORD unsigned int
#define QWORD unsigned long
#define BOOL unsigned char

#define TRUE 1
#define FALSE 0
#define NULL ((void *) 0)

#pragma pack(push, 1)

// 비디오 모드 중 텍스트 모드 화면을 구성하는 자료구조
typedef struct kvideo_char {
    BYTE value;
    BYTE attribute;
} kvideo_char_t;

#pragma pack(pop)

#endif //MINTOS64_TYPES_H
```
- main.c
```c
#include "types.h"

void kprint_string(int x, int y, const char *string);

int main(void) {
    kprint_string(0, 3, "C Language Kernel Started");
    while (1);
    return 0;
}

void kprint_string(int x, int y, const char *string) {
    kvideo_char_t *screen = (kvideo_char_t *) 0xb8000;
    int i;

    screen += 80 * y + x;
    for (i = 0; *string != '\0'; i++) {
        screen[i].value = string[i];
    }
}
```

**Comment by ybjeon01** [comment]
@EugeneChung, 안녕하세요.

저도 코드 일부분만 봐서는 문제를 정확히 파악할 순 없지만 kprint_string 함수 구현이 조금 잘못된 게 보입니다. 


```
void kprint_string(int x, int y, const char *string) {
    kvideo_char_t *screen = (kvideo_char_t *) 0xb8000;
    int i;

    screen += 80 * y + x;
    
 
    // 첫번째 문자만 참조하기 때문에 for loop문이 끝나지 않을 수 있습니다.
    /* for (i = 0; *string != '\0'; i++) { */

    for (i = 0; string[i] != '\0'; i++) {
        screen[i].value = string[i];
    }
}
```

이게 문제를 고쳐줄 거라고 기대는 안하지만 한번 이 코드만 수정하고 다시 실행해보시겠어요?

저도 한번 코드 컴파일하고 QEMU에 올려보고 싶은데 코드 공유 가능할까요?

**Comment by EugeneChung** [comment]
@ybjeon01
제가 올려둔 문제 외에, QEMU로 부팅해놓고 시간 지나면 화면이 싹 지워지는 현상도 있는데 말씀해주신 코드 때문이네요.
물론 그거 고쳐서 돌려도 2자 짤리는 건 동일합니다.

전체 코드는 https://github.com/EugeneChung/MintOS64 master branch에 올려둔 상태입니다.
일부러 cmake 사용법을 익혀보려고 cmake 빌드 스크립트를 만들어 보고 있습니다.
저는 CLion을 쓰고 있는데 MacOS 상에서 command line 명령은 아래와 같네요.
`/Applications/CMake.app/Contents/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEPENDS_USE_COMPILER=FALSE -G "CodeBlocks - Unix Makefiles" /Users/eugene/project/private/mintos64
`

**Comment by ybjeon01** [comment]
찾았습니다. 범인은 [EntryPoint.asm](https://github.com/EugeneChung/MintOS64/blob/develop/kernel32/src/EntryPoint.asm)이였네요. 마지막 줄을 보시면

```Assembly
times 510 - ($ - $$) db 0x00
```

라고 정의되어있습니다.  이걸 

```Assembly
times 512 - ($ - $$) db 0x00
```

바꿔주면 되겠습니다. C언어 코드에서 변환된 기계어가 2byte 앞으로 밀려서 저장이 되었습니다. 근데 코드가 운이 좋게(?) invalid opcode error가 안뜨고 무사히 실행이 됐네요.

**Comment by EugeneChung** [comment]
@ybjeon01 오.. 그렇네요. 감사합니다. 덕분에 어떤 부분에서 문제를 살펴봐야 할지 직관을 얻은 것 같습니다.
저는 공부하면서 해보는 거지만 이걸 업으로 한다고 생각하면.. 디버깅이 까다로워서 일 진척이 쉽지 않겠습니다. ㅠㅜ

2 bytes 밀려서 코드가 실행되면서 static 공간상에 있는 `C Language Kernel Started`에서 C가 아닌 L을 가리켰겠네요.
그리고 맨앞 2bytes의 opcode는 kprint_string 호출하기 위해 준비하는 코드일 것 같은데.. 빠져도 큰 문제는 안 됐나 봅니다.
