### ISSUE TITLE
Ring 3

### ISSUE THREAD

**Issue by Juha3141** [kkamagui/mint64os#6]
IA-32e모드에서 Ring 3로 진입하려면 어떻게 해야하나요? 디스크립터 테이블에 DPL을 3으로 만든 후 Ring 3용 코드 세그먼트와 데이터 세그먼트를 만들면 되는건가요?

계속 질문해서 죄송합니다

**Comment by kkamagui** [comment]
안녕하세요, @Juha3141님.

말씀하신 내용대로 코드 세그먼트와 데이터 세그먼트를 만드신 다음, 각 세그먼트 셀렉터에 잘 넣어주시고 마지막으로 jmp 명령어를 수행하실 때 <Ring 3용 코드 세그먼트>:<점프할 주소>로 해주시면 됩니다. 데이터 세그먼트, 스택 세그먼트 등은 점프 하시기 직전에 넣어주시면 됩니다. ^^

**Comment by Juha3141** [comment]
네 감사합니다!
